# Numpy

- NumPy is a general-purpose array-processing package.
- Numpy was created to work with multidmensional arrays.
- It is the fundamental package for scientific computing with Python.
- It is open-source library.

# Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

- Arrays are very frequently used in data science, where speed and resources are very important.

In [1]:
# installing necessary library need following comand 
#  we use "!" before command (i.e. pip install) to avoid restrating the kernal
# !pip install numpy

In [2]:
#Importing necessary library
import numpy as np 

#### Array Creation

In [3]:
a = np.array(10)
type(a)

numpy.ndarray

##### Zero dimensional array

In [7]:
z = np.array(10)
z

array(10)

In [9]:
# checking dimensions 
z.ndim

0

##### One dimensional array

In [31]:
o = np.array([10,12,12,15])
print (o.ndim)
o

1


array([10, 12, 12, 15])

##### Two dimensional array

In [32]:
t = np.array([[10,10,12,14,15]])
print(t.ndim)
t

2


array([[10, 10, 12, 14, 15]])

##### Three dimensional array

In [26]:
th = np.array([[[10,12,14,15,16]]])
th

array([[[10, 12, 14, 15, 16]]])

In [25]:
th.ndim

3

##### Change the data type of the array elements.

In [27]:
a = np.array([10,15,52,54])

In [28]:
a.dtype

dtype('int32')

In [33]:
a = np.array([10,15,52,54], dtype = 'float')
print(a.dtype)
print('hello')
a

float64
hello


array([10., 15., 52., 54.])

# Other ways of creating an array
1. arange
2. linspace
3. zeros
4. ones
5. random

### 1.arange

In [45]:
a = np.arange(1, 21)
a

# prints all values from 1-20 excludes upper extreme

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
a = np.arange(1, 21, 2)
a

# prints alternates values (i.e 2nd values from the first one) from 1-20 excludes upper extreme.

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### 2.linspace
- What is the use of NumPy Linspace?

The NumPy linspace function creates sequences of evenly spaced values within a defined interval.

Essentally, you specify a starting point and an ending point of an interval, 

and then specify the total number of breakpoints you want within that interval (including the start and end points).

In [40]:
b = np.linspace(1,5,15)
b

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [47]:
b = np.linspace(1,5,15, retstep=True)
b

#  reststep gives the actual difference between 2 sequntial values of array created by linspace

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

### 3.zeros

In [48]:
z = np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

### 4.ones

In [51]:
ones = np.ones([5,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 4.Randaom
- has two sub functions rand and randint
- rand that gives randon numerical values
- and randint that gives integers only 

In [53]:
r = np.random.rand(5,5)
r

array([[0.78211666, 0.21096961, 0.79902477, 0.66123502, 0.02360835],
       [0.64854017, 0.64376033, 0.71084284, 0.77160542, 0.72038471],
       [0.16007297, 0.40268177, 0.25245734, 0.28023712, 0.61614788],
       [0.76304418, 0.94964481, 0.9306832 , 0.7509292 , 0.13599026],
       [0.09892113, 0.3310644 , 0.38921465, 0.2724602 , 0.04324854]])

In [54]:
r = np.random.randint(5, size = 10)
r

array([4, 1, 3, 4, 3, 3, 1, 1, 2, 1])

# Slicing and Indexing of arrays

In [55]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
#  slicing 
#         (0,0) (0,1) (0,2) 
# array([[1,      2,    3],
#        [4,      5,    6]])
#        (1,0)  (1,1) (1,2)

In [58]:
a[0,0]

1

In [59]:
a[1,2]

6

In [ ]:
#  values in range 

In [42]:
a[0,1:]

array([2, 3])

In [43]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [60]:
#  printing any two values with help of index

In [61]:
#1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [63]:
#3 and 4
a[[0,1],[2,0]]

array([3, 4])

# Reshaping the arrays 
- changing/moulding dimesions i.e. no.of rows or coloums

In [65]:
a = np.random.rand(5,2)
a

array([[0.48375279, 0.46271429],
       [0.64581117, 0.91243658],
       [0.53398425, 0.69959387],
       [0.89622179, 0.14517935],
       [0.08608879, 0.12705991]])

In [66]:
a.reshape(2,5)

array([[0.48375279, 0.46271429, 0.64581117, 0.91243658, 0.53398425],
       [0.69959387, 0.89622179, 0.14517935, 0.08608879, 0.12705991]])

In [67]:
a.reshape(10,1)
#  observe brackets 

array([[0.48375279],
       [0.46271429],
       [0.64581117],
       [0.91243658],
       [0.53398425],
       [0.69959387],
       [0.89622179],
       [0.14517935],
       [0.08608879],
       [0.12705991]])

In [68]:
a.reshape(1,10)
#  observe brackets 

array([[0.48375279, 0.46271429, 0.64581117, 0.91243658, 0.53398425,
        0.69959387, 0.89622179, 0.14517935, 0.08608879, 0.12705991]])

In [72]:
a.reshape(5,-1)
#  observe brackets 

array([[0.48375279, 0.46271429],
       [0.64581117, 0.91243658],
       [0.53398425, 0.69959387],
       [0.89622179, 0.14517935],
       [0.08608879, 0.12705991]])

# Aggregate Functions

- The Python numpy aggregate functions are sum, min, max, mean, average, product, median, standard deviation, variance,  percentile, and corrcoef.

In [73]:
a.min()

0.08608878858331859

In [74]:
a.std()

0.2876287086705322

In [75]:
a.var()

0.0827302740514779

In [76]:
a.mean()

0.4992842765460579

# Stacking 
- Stacking is used to join 2 different arrays.
- Vertical stacking
- Horizontal stacking

In [81]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,8,7])

In [79]:
#  ".hstalk" staks/adds/puts up arrays in one row i.e. horizontaly 
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 8, 7])

In [80]:
#  ".vstalk" staks/adds/puts up arrays in columes i.e. verticaly 
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 8, 7]])

In [ ]:
# end